Improve client updater UX
FAForever/client pull request #822
Opened 2017-08-08 04:05 UTC by duk3luk3

* Never show same version client already has as update
* Don't call old versions "updates"
* Don't show old versions by default

2017-08-08 19:44 UTC, Wesmania requested changes
Some nitpicks, one logic issue.

2017-08-08 19:44 UTC, Wesmania commented on src/client/updater.py
> +        have_server = len(server_releases) > 0
We can as well rely on the fact that empty lists evaluate to false and do 'if server_releases'.

2017-08-08 19:44 UTC, Wesmania commented on src/client/updater.py
> +        return have_server or notify_stable or notify_pre or notify_beta
I think we can rearrange that to use an if / if else / else with self.updater_branch (maybe add a 'version we're interested in' variable to make things easier). Also, are we supposed to use that 'downgrade' config variable here?

2017-08-08 19:44 UTC, Wesmania commented on src/client/updater.py
> +            labels = dict([('server', 'Server Version'), ('stable', 'Stable Version'), ('pre', 'Stable Prerelease'), ('beta', 'Unstable')])
Not the prettiest notation IMO

2017-08-08 19:44 UTC, Wesmania commented on src/client/updater.py
> +            preferIdx = -1
None would be nice too (just a personal preference / nitpick).

2017-08-08 19:44 UTC, Wesmania commented on src/client/updater.py
> +                currIdx = currIdx + 1
We can just iterate over enumerate(self.releases) instead.

2017-08-08 19:44 UTC, Wesmania commented on src/client/updater.py
> +    updater_downgrade = Settings.persisted_property('updater/downgrade', type=bool, default_value=False)
Why is it in 2 places at once? Is persisted_property capable of handling such a case (specifically does it update the other value when one of them changes)?

2017-08-08 19:44 UTC, Wesmania commented on src/client/updater.py
> +                        if not v < cv or cv < v
Longer variable names would help readability here IMO, something like 'current_version' and 'remote_version'. And I think operator precedence screwed us over here.

2017-08-09 00:23 UTC, duk3luk3 commented on src/client/updater.py
> +        have_server = len(server_releases) > 0
I prefer not to rely on falsyness.

2017-08-09 00:27 UTC, duk3luk3 commented on src/client/updater.py
> +        return have_server or notify_stable or notify_pre or notify_beta
* I don't see how to make the logic more concise without making it harder to understand. I don't think turning it into a cascade of if statements would help at all.
* No, this logic is meant for deciding whether we want to show the update dialog when the client starts.

2017-08-09 00:30 UTC, duk3luk3 commented on src/client/updater.py
> +    updater_downgrade = Settings.persisted_property('updater/downgrade', type=bool, default_value=False)
persisted_property is just a wrapper around Settings.get and Settings.set so yes, this is fine.

2017-08-09 00:31 UTC, duk3luk3 commented on src/client/updater.py
> +                        if not v < cv or cv < v
what screwed us here is that I left off the ':'. The precedence [is fine](https://docs.python.org/3/reference/expressions.html#operator-precedence).

2017-08-09 15:03 UTC, Wesmania commented on src/client/updater.py
> +        have_server = len(server_releases) > 0
It's fairly pythonic IMO, but your call.

2017-08-09 15:07 UTC, Wesmania commented on src/client/updater.py
> +        return have_server or notify_stable or notify_pre or notify_beta
We can change notify_* bools to check whether a given branch has a newer version (remove  the self.updater_branch check), then use self.updater_branch separately.

2017-08-09 15:07 UTC, Wesmania commented on src/client/updater.py
> +                        if not (release_version > client_release_versionersion):
Typo?

2017-08-09 15:17 UTC, merged